### ISSUE TITLE
Update awscli version

### ISSUE THREAD

**Issue by mithrandi** [deitch/mysql-backup#11]
The awscli version in the container doesn't support the newer regions like eu-west-2; I think you just need to trigger a rebuild of the container, since the awscli version isn't pinned. Might be a good idea to link it to the alpine repository to automatically rebuild to pick up security fixes and such.

**Comment by deitch** [comment]
Well, images should be immutable, so probably better just to trigger another build.

**Comment by deitch** [comment]
Closed via #12
