### ISSUE TITLE
Selecting database to dump

### ISSUE THREAD

**Issue by th0th** [deitch/mysql-backup#13]
First of all, thanks a lot for the image, it is awesome really.

Is it too much to ask to be able to select the database to backup? I want to backup only data related to my app, not the entire mysql auth data and such.

It can be set via an optional `DB_NAME` environment variable, if not set the current behaviour is used as default. How does it sound?

**EDIT:** In this case the user is `root`. So it has access to all databases.

**Comment by deitch** [comment]
> First of all, thanks a lot for the image, it is awesome really.

:-)

> It can be set via an optional DB_NAME environment variable, if not set the current behaviour is used as default. How does it sound?

Doesn't sound too difficult.

**Comment by deitch** [comment]
Closed via #14 

Merged in, but not pushing out to docker quite yet; need to clean up the test chain.

**Comment by deitch** [comment]
Pushed out. Enjoy.

**Comment by th0th** [comment]
Wow that was fast, thanks!
