### ISSUE TITLE
Allow to specify SMB credentials via "--env-file="

### ISSUE THREAD

**Issue by domtoupin** [deitch/mysql-backup#18]
Hi,

First of all thank you for your work, it looks terrific!

I took a quick look at both your doc and your code and couldn't help noticing that although secrets are well protected for both mysql and AWS credentials, they are nonetheless in plain sight when its comes down to SMB...

Could it be possible for you to fix this?

I might be able to tackle this later, but I will first try setting this to backup our databases :-)

**Comment by deitch** [comment]
> First of all thank you for your work, it looks terrific!

Quite welcome. And thanks to the various client projects I worked on that let me open-source it. :-)

What do you mean by "well protected for both mysql and AWS credentials" and by "in plain sight when its comes down to SMB." Always happy to improve security, however minor, but can you point out the differences?

**Comment by domtoupin** [comment]
What I meant, was that for both mysql and AWS, the username and password can currently be specified separate for the host/uri, while for SMB user and password must be specified within the uri... However, I took another look at the code and I realized that one of my assumptions was wrong; I thought that since the user and password could not be specified on their own for SMB, that they would be in "plain sight" in the target uri... However, I see now that one could put the whole target uri in an env-file...

So, in the end, what I meant/wanted was to be able to specify the username and password separate from the uri in all cases...

**Comment by deitch** [comment]
> So, in the end, what I meant/wanted was to be able to specify the username and password separate from the uri in all cases...

Well that makes sense. Let's see what we can do.
