### ISSUE TITLE
support s3 storage

### ISSUE THREAD

**Issue by clescot** [deitch/mysql-backup#2]
Hi,
thanks for your great work.
One useful feature would be to support s3 storage for backup and restore.
For inspiration, another project (https://github.com/iainmckay/docker-mysql-backup) support s3 storage via awscli (but without a cron feature like yours).

best regards,
Charles.

**Comment by deitch** [comment]
Well, that is an interesting idea. Just use the env vars to set AWS_ACCESS_KEY and AWS_SECRET_KEY as well as bucket and path.

@ianmckay, do you want to collaborate on merging these?
