### ISSUE TITLE
DBSERVER cannot be set to external database

### ISSUE THREAD

**Issue by shosk33** [deitch/mysql-backup#21]
Currently, the entrypoint does not allow for the `DBSERVER` variable to be overridden.  This causes an issue when using a database external to a docker-compose file.

https://github.com/deitch/mysql-backup/blob/3e80b51baa4e64853692bf9f5cab05b015ebb7e5/entrypoint#L18-L19

It would be helpful to have an environment variable that could set this value if provided.
For example:
`DBSERVER=${DB_SERVER:-db}`

**Comment by deitch** [comment]
I guess that makes sense. Even external to the compose file you can use it, if you are using swarm or kubernetes services. But I see no reason why not.

Open a PR for it?

**Comment by shosk33** [comment]
Yeah, I'll open a PR

**Comment by shosk33** [comment]
Added https://github.com/deitch/mysql-backup/pull/22 to address this issue

**Comment by deitch** [comment]
Closed via #22
