### ISSUE TITLE
DB_PASS should be optional

### ISSUE THREAD

**Issue by th0th** [deitch/mysql-backup#23]
I am using rancher server's image, it has its own MySQL server in the container and it is not password protected. Even if I don't set `DB_PASS` I get this error:

```
mysqldump: Got error: 1045: "Access denied for user 'root'@'***' (using password: YES)" when trying to connect
```

Is there a way not to pass password?

**Comment by deitch** [comment]
Rancher server does not have a password?

**Comment by deitch** [comment]
> Rancher server does not have a password?

That seems strange to me, unless they only listen on a Unix domain socket, but looking at [this](https://github.com/rancher/rancher/blob/master/server/service/mysql/run#L4) it appears they do not? That seems strange.

Either way, though, no objection to enabling support for not passing a password.

**Comment by deitch** [comment]
Just about done redoing the Makefile and tests, and we will roll it in.

**Comment by deitch** [comment]
Closed via https://github.com/deitch/mysql-backup/pull/24

**Comment by deitch** [comment]
Pushing out now

**Comment by th0th** [comment]
Thank you!
