### ISSUE TITLE
Reading environment variables from file

### ISSUE THREAD

**Issue by th0th** [deitch/mysql-backup#26]
While using rancher secrets, data to pass into environment variables are mounted in a file on `/run/secrets`. Some images on docker hub like `mysql` supports this kind of variable passing, e.g. you pass an environment variable `MYSQL_USERNAME_FILE=/run/secrets/MYSQL_USERNAME` and on entrypoint it read the environment variable from that file. Is it possible to get the same behaviour with this image?

Relevant part from rancher docs: http://rancher.com/docs/rancher/latest/en/cattle/secrets/#docker-hub-images

And this is an example entrypoint that reads environment variables from files (see`file_env` function): 
https://github.com/docker-library/mysql/blob/0590e4efd2b31ec794383f084d419dea9bc752c4/5.7/docker-entrypoint.sh#L25

**Comment by deitch** [comment]
So the assumption is that the secrets would be provided by some other mechanism? Rather than using 

```
docker run -e MY_SECRET=a_deep_dark_secret ....
```

You would instead do:

```
docker run -e MY_SECRET_FILE=/run/secrets/my_secret ...
```

and then something (`-v`, or swarm or kube, etc.) would mount the secret there?

No objection to it, looks good. Open a PR?

**Comment by th0th** [comment]
Yes, the case is exactly like you explained. I'll have a look at entrypoint and see what I can do, thanks.
