### ISSUE TITLE
add a version in DockerFile

### ISSUE THREAD

**Issue by clescot** [deitch/mysql-backup#3]
Hi,
in the docker hub repository, there is only the latest release.
Can you add a version to your release, to get a precise one and not the 'latest' release?

thanks in advance,

Charles.

**Comment by deitch** [comment]
@clescot funny you raise that. Just this past week, I was trying to get Docker Hub to recognize and automatically build both a versioned number and latest when there is a new commit, and I couldn't get it to work. 

Look at the latest tagging:

````
$ g tag
0.5
0.5.1
0.5.2
0.5.3
0.6.0
````

So you can see that the versions are tagged. And then docker hub:


![1](https://cloud.githubusercontent.com/assets/282526/13030699/a2b7d814-d281-11e5-94f7-5b1a95df922b.png)
![2](https://cloud.githubusercontent.com/assets/282526/13030700/a5d7e7e6-d281-11e5-98b9-31fe77d20ab7.png)
![3](https://cloud.githubusercontent.com/assets/282526/13030701/a9db3d7a-d281-11e5-8089-a5efd5c2a43c.png)




So it appears to be correct, but doesn't do tagged builds! Any idea how to get this to work correctly?

**Comment by deitch** [comment]
Any idea how to get it work?
