### ISSUE TITLE
Container linking shouldn't be the recommended way

### ISSUE THREAD

**Issue by th0th** [deitch/mysql-backup#30]
According to [docker docs](https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/), container linking (with `--link` flag) is considered legacy. It is even written that it can be removed in future versions.

I think we should make `DBSERVER` a variable in `entrypoint` and update the readme with instructions to create mysql and mysql-backup containers in the same docker network. What do you say?

**Comment by deitch** [comment]
Nice. See #31 

Will merge as soon as CI is green.
