### ISSUE TITLE
DB_DUMP_FREQ is used fully after the backup causing the effective start time slide into the future

### ISSUE THREAD

**Issue by seli** [deitch/mysql-backup#38]
When setting DB_DUMP_FREQ to 1440 you expect the backup to be taken daily at the same time, namely the time configured in DB_DUMP_BEGIN.

On line 113 in entrypoint, a correct calculation is being made to calculate the time so the first backup can start at the expected time. 
But!
On line 204 in entrypoint, after the backup finished (which can take f.e. 2 hours) the DB_DUMP_FREQ is used completely without extracting the already spend time for taking the backup.

It would be nice if the code, starting on line 113, can be reused on line 204 to recalculate the waittime so the next backup will start again at the same time as the previous one.

----

Code of entrypoint on line 113

     if [[ $DB_DUMP_BEGIN =~ ^\+(.*)$ ]]; then
       waittime=$(( ${BASH_REMATCH[1]} * 60 ))
     else
       target_time=$(date --date="${today}${DB_DUMP_BEGIN}" +"%s")
    
       if [[ "$target_time" < "$current_time" ]]; then
         target_time=$(($target_time + 24*60*60))
       fi
     
       waittime=$(($target_time - $current_time))
     fi

    # If RUN_ONCE is set, don't wait
      if [ -z "${RUN_ONCE}" ]; then
        sleep $waittime
      fi

----

Code of entrypoint on line 204    

    sleep $(($DB_DUMP_FREQ*60))

**Comment by deitch** [comment]
Ah. So line 204 should not be "sleep `$DB_DUMP_FREQ*60`", but instead "sleep `$DB_DUMP_FREQ*60 - time_it_took_to_run_last_backup`? 

That is bad pseudo-code, obviously, but the idea being that if `time_it_took` is small, then it doesn't matter, but if `time_it_took` is large, then we can have a drift between each run of `time_it_took`?

**Comment by deitch** [comment]
I guess we would determine the epoch timestamp when we come out of sleep, then after backup runs add the `DB_DUMP_FREQ` to the _start_ time to get the end time, and sleep until that?

Open a PR?

**Comment by deitch** [comment]
Closed via #39
