### ISSUE TITLE
Post-post-backup?

### ISSUE THREAD

**Issue by Notifium** [deitch/mysql-backup#42]
Hi,

I'm currently saving a backup directory on the local server, and have a script which retains backup according to a defined schedule. ie, the backup is done hourly, and the script retains 48x hourly backups, then each 24 hours it copies the backup to a daily archive folder, where it saves 14x daily backups. Each 7 days it copies the latest backup to a weekly archive folder, etc.

Is there any way to automatically trigger this script from the docker image, so that it fires only after the mysql-backup copies the file to it's final upload location defined by $DB_DUMP_TARGET?

Regards,
Andy

**Comment by Notifium** [comment]
Ah, I think I've resolved it. I'll use the post-backup script to copy the backup file into the daily/weekly/monthly folders first, then let the entrypoint script do the normal backup to the standard defined location.

I'll close the issue.

**Comment by deitch** [comment]
Hi @Notifium . Yep, that is how I would do it. Didn't have time to respond - was at KubeCon this week - but you got it.
