### ISSUE TITLE
strange generating of dumps

### ISSUE THREAD

**Issue by michalbehun** [deitch/mysql-backup#47]
Hello. I have problem with generating sql dump for rancher server.
My backup container is running with command:
```
docker run -d --restart=always -e DB_USER=cattle -e DB_PASS=cattle -e DB_DUMP_BEGIN=2330 -e DB_DUMP_TARGET=/db -e DB_SERVER=rancher-sanbox -v /mnt/backup-nfs/rancher_db/sandbox:/db --name rancher-backup-sandbox --network rancher-network deitch/mysql-backup
```

When I list content of dump folder, there are some files, that are only 20bytes in size and have strange time of creation:
```
-rw-r--r--. 1 root root 7965408 May 31 01:30 db_backup_20180530233000.gz
-rw-r--r--. 1 root root      20 Jun  1 09:03 db_backup_20180601070339.gz
-rw-r--r--. 1 root root      20 Jun  1 10:11 db_backup_20180601081147.gz
-rw-r--r--. 1 root root      20 Jun  1 10:16 db_backup_20180601081619.gz
-rw-r--r--. 1 root root 8073738 Jun  2 01:30 db_backup_20180601233000.gz
-rw-r--r--. 1 root root      20 Jun  2 10:16 db_backup_20180602081619.gz
-rw-r--r--. 1 root root 8016356 Jun  3 01:30 db_backup_20180602233001.gz
-rw-r--r--. 1 root root      20 Jun  3 10:16 db_backup_20180603081619.gz
-rw-r--r--. 1 root root 8261452 Jun  4 01:30 db_backup_20180603233000.gz
-rw-r--r--. 1 root root      20 Jun  4 10:16 db_backup_20180604081619.gz
-rw-r--r--. 1 root root 8050066 Jun  5 01:30 db_backup_20180604233000.gz
-rw-r--r--. 1 root root      20 Jun  5 10:16 db_backup_20180605081619.gz
```

Shift in timestamp in filename and real creation time is because our server is running in CEST time zone and inside docker containers is UTC. Can be this source of my problems?

Thank you for your response.
Best regards
Michal Behúň

**Comment by deitch** [comment]
Possibly, but unlikely. I suspect the backup is failing. Two suggestions:

1. Get one of those files and try to `cat` it (possibly `gunzip` first).
2. Enable debug on the run to see output logs. 

You also might want to look at the logs without debug. I suspect an error somewhere.

**Comment by michalbehun** [comment]
It contains only empty file.
`gunzip db_backup_20180601070339.gz`
`-rw-r--r--. 1 root root       0 Jun  1 09:03 db_backup_20180601070339`

`docker logs rancher-backup-sandbox`
DB_PORT not provided, defaulting to 3306
Starting at Wed May 30 14:05:28 UTC 2018
DB_PORT not provided, defaulting to 3306
Starting at Fri Jun 1 07:03:40 UTC 2018
DB_PORT not provided, defaulting to 3306
Starting at Fri Jun 1 08:16:17 UTC 2018
DB_PORT not provided, defaulting to 3306
Starting at Tue Jun 5 09:17:25 UTC 2018
DB_PORT not provided, defaulting to 3306
Starting at Tue Jun 5 09:18:12 UTC 2018

Should I paste log with DB_DEBUG=TRUE directly here?

**Comment by deitch** [comment]
> It contains only empty file.

Yeah, that happens when the backup fails. I had that when working against mysql 8.0.4+, which uses a new default authentication mechanism and can break things. 

It is surprising that there is nothing in the logs, but it is possible the non-debug mode is a little too aggressive. 

Definitely enable `DB_DEBUG` and let's see. It _might_ dump out credentials, so do be careful when cutting/pasting into here.

**Comment by michalbehun** [comment]
I ran
`docker run -d --restart=always -e DB_USER=cattle -e DB_PASS=cattle -e DB_DUMP_TARGET=/db -e DB_SERVER=rancher-sanbox -e DB_DUMP_DEBUG=TRUE -e DB_DUMP_FREQ=2 -v /mnt/backup-nfs/rancher_db/sandbox:/db --name bcptest --network rancher-network deitch/mysql-backup`

Logs are here, unoftunately, all backups are probably good
[logs.txt](https://github.com/deitch/mysql-backup/files/2072092/logs.txt)

-rw-r--r--. 1 root root 8034753 Jun  5 12:57 db_backup_20180605105717.gz
-rw-r--r--. 1 root root 8034735 Jun  5 12:59 db_backup_20180605105917.gz
-rw-r--r--. 1 root root 8034746 Jun  5 13:01 db_backup_20180605110117.gz
-rw-r--r--. 1 root root 8034737 Jun  5 13:03 db_backup_20180605110317.gz
-rw-r--r--. 1 root root 8034735 Jun  5 13:05 db_backup_20180605110517.gz

But I wonder, if the dump finished OK, my mysql volume has around 219MB and zipped dump only 8MB
Is this normal?

**Comment by deitch** [comment]
you should format those logs with triple-backticks to make it easy to read.

> my mysql volume has around 219MB and zipped dump only 8MB
Is this normal?

It can be. The backups are mostly text, which compresses very well. But check it. `gunzip` a file and check contents.

**Comment by michalbehun** [comment]
```
-- MySQL dump 10.16  Distrib 10.1.32-MariaDB, for Linux (x86_64)
--
-- Host: rancher-sanbox    Database:
-- ------------------------------------------------------
-- Server version       5.5.55-0ubuntu0.14.04.1

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Current Database: `cattle`
--

CREATE DATABASE /*!32312 IF NOT EXISTS*/ `cattle` /*!40100 DEFAULT CHARACTER SET utf8 */;

USE `cattle`;

...

-- Dump completed on 2018-06-05 10:44:56
```
It looks dump is OK. I will schedule backups the same way, but in debug mode and try to catch failed one.
This also happened with our second rancher server
```
-rw-r--r--. 1 root root 15997983 May 31 01:45 db_backup_20180530234500.gz
-rw-r--r--. 1 root root       20 Jun  2 01:45 db_backup_20180601234500.gz
-rw-r--r--. 1 root root       20 Jun  3 01:45 db_backup_20180602234500.gz
-rw-r--r--. 1 root root       20 Jun  4 01:45 db_backup_20180603234500.gz
-rw-r--r--. 1 root root       20 Jun  5 01:45 db_backup_20180604234500.gz
```

**Comment by michalbehun** [comment]
Well, backups were generated normally, second one was my mistake, I forgot to connect rancher container to network along with the backup container.
By the way, when my containers were connected to standard bridge docker0 network only, backup could not resolve hostname of rancher, despite rancher is started with --name. If this is normal behavior to connect containers to custom network, like you recommend in example with docker-compose, maybe add this to another examples.
Anyway, I will wait couple of days, if some of backups will fail, otherwise I will close this issue.

**Comment by deitch** [comment]
> By the way, when my containers were connected to standard bridge docker0 network only, backup could not resolve hostname of rancher, despite rancher is started with --name

I believe it is. I think docker only adds name resolution by container name when on a custom network. 

```
$ docker run -d --name=nginx nginx
Status: Downloaded newer image for nginx:latest
a527b94455a1ebde2ccd267c72e1380051ff027ad8525063bf58a4cf42683080
$ docker run -it --rm alpine:3.6 sh
# apk --update add bind-tools
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
(1/4) Installing libgcc (6.4.0-r5)
(2/4) Installing libxml2 (2.9.7-r0)
(3/4) Installing bind-libs (9.11.3-r0)
(4/4) Installing bind-tools (9.11.3-r0)
Executing busybox-1.27.2-r7.trigger
OK: 9 MiB in 15 packages
/ # dig www.google.com

; <<>> DiG 9.11.3 <<>> www.google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 62349
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;www.google.com.			IN	A

;; ANSWER SECTION:
www.google.com.		152	IN	A	172.217.23.132

;; Query time: 1 msec
;; SERVER: 192.168.65.1#53(192.168.65.1)
;; WHEN: Wed Jun 06 14:37:00 UTC 2018
;; MSG SIZE  rcvd: 48

/ # dig nginx

; <<>> DiG 9.11.3 <<>> nginx
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 49906
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;nginx.				IN	A

;; Query time: 103 msec
;; SERVER: 192.168.65.1#53(192.168.65.1)
;; WHEN: Wed Jun 06 14:37:02 UTC 2018
;; MSG SIZE  rcvd: 23

```

**Comment by michalbehun** [comment]
OK. Everything is looking good. I guess we can close this one.

**Comment by deitch** [comment]
Sounds good. If you run up against issues again, just open a new one.
