### ISSUE TITLE
Custom mysqldump arguments appear to be ignored

### ISSUE THREAD

**Issue by kabudu** [deitch/mysql-backup#51]
First of all, thanks for a great tool!

It appears that the custom mysqldump arguments passed as environment variables are not getting used.

On the following line, I can see you are expanding them into the ```DUMPVARS``` variable: https://github.com/deitch/mysql-backup/blob/68a0a4adbe1e75f4a39ea07326187403ce4bea04/entrypoint#L51

but that variable isn't being used on the following line or anywhere in the entrypoint script: https://github.com/deitch/mysql-backup/blob/68a0a4adbe1e75f4a39ea07326187403ce4bea04/entrypoint#L184

Am I missing something obvious, or is that really the case?

**Comment by deitch** [comment]
Yeah. The option was added in [this PR](https://github.com/deitch/mysql-backup/pull/40), specifically [here](https://github.com/deitch/mysql-backup/pull/40/files#diff-eeadbb5367edd2912b1c1cde5982ab4dR164), but looks like it disappeared in some later PR. 

Digging through it (never fun), I cannot figure out where it got lost. No other PR seems to do it. Some bad merge somewhere? Got to look by commits.

**Comment by deitch** [comment]
Ah, here we go, it is #29. Will need to fix that.

**Comment by deitch** [comment]
Thanks for catching.

**Comment by kabudu** [comment]
Thanks for the quick resolution.
