### ISSUE TITLE
Add support for upload via SSH/SCP/SFTP

### ISSUE THREAD

**Issue by extremeshok** [deitch/mysql-backup#57]
Basically uploading via SSH / SCP / SFTP

Either by providing credentials (user, pass, server, port, target_folder) or with a ssh key, user + keyfile + server + port + target folder.

Thanks

**Comment by deitch** [comment]
I think this is a great idea. Definitely open for a Pull Request on it. Happy to collaborate.

**Comment by extremeshok** [comment]
ping to keep this alive
