### ISSUE TITLE
Encrypt gzip file wiht password

### ISSUE THREAD

**Issue by Robbe64** [deitch/mysql-backup#58]
It would be nice if I could configure the backup to be encrypted with a specified password.

**Comment by deitch** [comment]
Why not use post-processing? https://github.com/deitch/mysql-backup#backup-pre-and-post-processing

**Comment by Robbe64** [comment]
Sure I could use post-processing but running a second compression step is not as smart as just passing a password to the existing compression machanism.

**Comment by deitch** [comment]
I am not sure what you mean. The compression is gzip. As far as I know, the canonical way to encrypt gzip files as to pass them through an encryption after (or before) compressing.

**Comment by Robbe64** [comment]
Oh, ok. Didn't know that.
But, an included functionality would still be nice.

**Comment by deitch** [comment]
It would, indeed, but the number and variety of encryption mechanisms is so high as to make it challenging. Everyone would want something else, so post-processing probably is the easiest way to satisfy.

Still and all, if you have some ideas and want to open a PR, would welcome it.

**Comment by Robbe64** [comment]
Got encyprtion working but how to decrypt the archive before restoring the backup and after downloading the file via smb?

**Comment by deitch** [comment]
How about restore pre- and post-processing?

**Comment by deitch** [comment]
https://github.com/deitch/mysql-backup#restore-pre-and-post-processing

**Comment by Robbe64** [comment]
Pre-restore is called before the backup file is downloaded and post-restore after the mysql restore. From my point of view the pre-processing must happen after downloading the backup file and before restore to my mysql db.

**Comment by deitch** [comment]
Good point.

Open a new issue raising this, maybe with a diagram and a simple sample of how it doesn't work.
