### ISSUE TITLE
Permissions error when moving gzipped file to dump local path

### ISSUE THREAD

**Issue by j-d-b** [deitch/mysql-backup#61]
I'm seeing
```
mv: can't create '/db-backup/db_backup_20181102020657.gz': Permission denied
```

When running from the `deitch/mysql-backup` image. Everything else seems to be working as expected from viewing the DB_DUMP_DEBUG=true output.

I tried cloning the repo and removing the following lines from the Dockerfile. This fixed the issue.
```
# set us up to run as non-root user
RUN groupadd -g 1005 appuser && \
    useradd -r -u 1005 -g appuser appuser
USER appuser
```

I'm starting `mysql-backup` with `docker-compose` and mounting a volume to persist this data on the host. Is there something I'm missing in my setup that's needed to give the `mysql-backup` user adequate privileges?

**Comment by kabudu** [comment]
Hi! See the discussion here: https://github.com/deitch/mysql-backup/issues/60

**Comment by deitch** [comment]
Thanks for jumping in @kabudu . 

I think the real issue here is, "needs documentation." It **definitely** was the right thing to do to make the default user non-root. It just needs better documentation. Going to leave this open while I put in a PR.

**Comment by deitch** [comment]
Documented in #62
