### ISSUE TITLE
Add support for Percona XtraBackup

### ISSUE THREAD

**Issue by patakijv** [deitch/mysql-backup#63]
Reviewing some options, I like the direction of this solution for automating mysql backups within our docker-compose setup. One concern is that `mysqldump` pauses the database and for large databases this can be an issue.

Can you consider adding the Percona's XtraBackup in the Docker image and have it be the low level backup command (or optionally implemented via an environment variable) that is executed instead of `mysqldump`? This would allow hot backups without pausing the database transactions, not to mention open the door for other features and enhancements if you wanted to down the road.

**Comment by deitch** [comment]
Oh, I like that. Definitely make it an env var controlled option, in case someone is working with an engine that doesn't support it, and so as not to break anything that works now.

Want to open a PR?

**Comment by patakijv** [comment]
Hey @deitch, I meant to post it as a suggestion for enhancement, not that I was already working on it. I've updated the title and wording to make that more clear. Its not yet sure if this is my final decision for the solution for our projects or if I have the bandwidth right now to work on it ourselves. I will consider though and if I do work on it we will certainly submit a PR. If someone else is closer to making a change like this to include an option for hot dump/backup, I would certainly like to test it as part of my review of options for docker-compose based mysql backup.

**Comment by deitch** [comment]
I had an interesting discussion about this at a conference today. Someone else also suggested that it was a good approach in general, although he also makes a point of having multiple slave servers and always doing the dump on the slaves. For that matter, on a different set of servers, he also runs [zfs](http://open-zfs.org/) and just does snapshots without any backup at all.

> if I have the bandwidth right now to work on it ourselves

Not sure here either. Will try to look into it when we can. I think it is a great idea for an option though.
