### ISSUE TITLE
give single dump file name of db

### ISSUE THREAD

**Issue by michabbb** [deitch/mysql-backup#76]
hey avi,

since you added a big tar file, with individual dumps inside #64 - i really expected to see that the individual database dump (*.sql) have
the name of the database. you added the timestamp, which is really really great - but now - because the file is called `backup_xxxxxxx.sql`
and not `mydatabase_xxxxxx.sql` - i have no idea whats inside this dump. i really appriciate if you could change "backup" to the name of database that has been dumped here 😏 

![image](https://user-images.githubusercontent.com/3524595/51051495-3486a480-15d4-11e9-96f1-70e923e3b2df.png)

*THANKS*

**Comment by deitch** [comment]
Actually, it does, when you selectively choose individual databases, or when you ask to dump file per database via `DB_DUMP_BY_SCHEMA`. But if you just say, "dump them all", then there is no database name.

If you want to modify it further, why not use the [source file name customization](https://github.com/deitch/mysql-backup#custom-backup-source-file-name) ?

**Comment by michabbb** [comment]
pardon, i missed `DB_DUMP_BY_SCHEMA` here 🙈 will try it....

**Comment by michabbb** [comment]
@deitch i cannot confirm, that this is working. my container runs with the following options (docker inspect output):

```
         "Env": [
                "COMPRESSION=bzip2",
                "DB_DUMP_BEGIN=0415",
                "MYSQLDUMP_triggers",
                "DB_USER=root",
                "DB_NAMES=my_database",
                "MYSQLDUMP_opt",
                "MYSQLDUMP_skip-lock-tables",
                "DB_DUMP_BY_SCHEMA=true",
                ......
            ],
```
and this results in a backup like this:

![image](https://user-images.githubusercontent.com/3524595/51084599-d15c5580-172c-11e9-9594-045d1479bb8d.png)

as u understand you correctly: the file `20190113041501.sql` should be named `my_database_20190113041501.sql`.
what am i dong wrong?

and if i use more than one database, are they seperated by `,` or whitepsace, because i don´t get this by the readme.
and i am still not sure my `MYSQLDUMP_` params are correct used. would be happy if u could take a look into #75 .

*THANKS!*

**Comment by michabbb** [comment]
confirmed, works now 👍 ✔️
