### ISSUE TITLE
suggestion: give main tar-file a different name

### ISSUE THREAD

**Issue by michabbb** [deitch/mysql-backup#77]
hi again,

similar to #76 - it´s important to have individual filenames. let´s say i have 5 hosts, i use your script on every of these.
i copy all backups to a NAS into one single directory. this folder will look like:

```
-rw-r--r-- 1 1005 1005 103M Jan  6 21:14 db_backup_20190106201342.gz
-rw-r--r-- 1 1005 1005 103M Jan  7 05:16 db_backup_20190107041502.gz
-rw-r--r-- 1 1005 1005 103M Jan  8 05:16 db_backup_20190108041502.gz
-rw-r--r-- 1 1005 1005 104M Jan  9 05:16 db_backup_20190109041501.gz
-rw-r--r-- 1 1005 1005 105M Jan 10 05:18 db_backup_20190110041500.gz
-rw-r--r-- 1 1005 1005  74M Jan 11 05:18 db_backup_20190111041500.bz2
-rw-r--r-- 1 1005 1005  74M Jan 11 18:28 db_backup_20190111172434.tbz2
```

now i need a backup for host "HOST5" - HOW shall i find the backups of any of my hosts ? 😏 no chance.
if you could add a new ENV VAR like "BACKUPNAME" i could use that and the folder would look like:

```
-rw-r--r-- 1 1005 1005 103M Jan  6 21:14 db_backup_host1_20190106201342.gz
-rw-r--r-- 1 1005 1005 103M Jan  7 05:16 db_backup_host_120190107041502.gz
-rw-r--r-- 1 1005 1005 103M Jan  8 05:16 db_backup_host1_20190108041502.gz
-rw-r--r-- 1 1005 1005 104M Jan  9 05:16 db_backup_host2_20190109041501.gz
-rw-r--r-- 1 1005 1005 105M Jan 10 05:18 db_backup_host3_20190110041500.gz
-rw-r--r-- 1 1005 1005  74M Jan 11 05:18 db_backup_host4_20190111041500.bz2
-rw-r--r-- 1 1005 1005  74M Jan 11 18:28 db_backup_host5_20190111172434.tbz2
```

that would be very comfortable to read and would avoid filename collisions.

*THX*

**Comment by kabudu** [comment]
> do i have to use the `/scripts.d/target.sh` here ? 🤔

Yup! That's basically what it was built for!

**Comment by michabbb** [comment]
@kabudu thanks, okay. but maybe @deitch can consider this suggestion of using a seperate ENV for simple usage anway 😏 the script is nice, if you need variables in the name. but i guess in most cases, you only need an "identifier", therefor a script is "overkilled" (in my eyes) 😏

**Comment by deitch** [comment]
I don't think the script is overkill here. For your use case, you want to rename it this way; we have others who want to rename it other ways. All are legitimate, for each use case. I don't want to have to include (and maintain) every kind of possible logic, so let people rename it using their scripts. It is easy to do with other containers as well.
