### ISSUE TITLE
Update to latest alpine

### ISSUE THREAD

**Issue by chiefy** [deitch/mysql-backup#8]
Just ran into an issue w/ DNS in docker cloud that's fixed w/ alpine:3.4

**Comment by deitch** [comment]
Ah, yes, DNS. The number of times that has caused issues for me in docker, the number of issues raised on GitHub. :-)

Thanks for pointing it out. I am patching now.

**Comment by deitch** [comment]
Pushed out. It should automatically push to docker hub as well, but I don't find it pushes nicely, so I will push manually.

**Comment by chiefy** [comment]
thanks @deitch ! 👍
