### ISSUE TITLE
which mysql versions does it support?

### ISSUE THREAD

**Issue by jiskreq** [deitch/mysql-backup#84]
which mysql versions does it support?
how to set for specific mysql version?

**Comment by kabudu** [comment]
It currently only supports `mysql 5.7.*`. See this PR for mysql 8 support once Alpine 3.9 goes GA! https://github.com/deitch/mysql-backup/pull/80

**Comment by jiskreq** [comment]
@kabudu  how can i change the version for lowest or some other?

**Comment by deitch** [comment]
It should be able to handle mysql less than 5.8, but I am not 100% sure about the cross-compatibilities of `mysql` and `mysqldump` with `mysqld` versions. 

In any case, if you need specific compatibility with much older versions that are not supported in the latest `mysqldump`, there is the `--compatible=` flag that you can pass using `MYSQLDUMP_OPTS="--compatible=..."`

See [here](https://dev.mysql.com/doc/refman/5.7/en/mysqldump.html#option_mysqldump_compatible)

**Comment by deitch** [comment]
#80 is merged in.
